# Generated by Django 4.1.6 on 2023-08-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nikname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
