# Generated by Django 4.1.6 on 2023-08-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_user_email_verified_user_mobile_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
