# Generated by Django 4.1.6 on 2023-08-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_user_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nikname',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
