# Generated by Django 4.1.6 on 2023-09-04 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_alter_usermessagereply_options_remove_user_fcm_token_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessagereply',
            options={'ordering': ['sent_date']},
        ),
    ]
