# Generated by Django 4.1.6 on 2023-09-08 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_alter_usermessagereply_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_inbox_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermessagereply',
            name='reply_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermessagereply',
            name='reply_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_replies', to='user_app.usermessage'),
        ),
    ]
