# Generated by Django 4.1.6 on 2023-09-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_alter_usermessage_from_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nikname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(default=966, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
