# Generated by Django 4.1.6 on 2023-09-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_login_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_logs',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
