# Generated by Django 4.1.6 on 2023-08-20 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0002_post_category_post_created_by_post_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='post_app.sub_category'),
        ),
    ]
