# Generated by Django 4.1.6 on 2023-08-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0003_post_sub_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post_category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='post_category',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
