# Generated by Django 4.1.6 on 2023-09-16 10:37

from django.db import migrations
import django_resized.forms
import post_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0011_alter_myfavorite_post_alter_myfavorite_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_images',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1920, 1080], upload_to=post_app.models.Post_Images.upload_file),
        ),
    ]
